# Generated by Django 5.1.7 on 2025-03-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_account_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
    ]
