# Generated by Django 5.1.7 on 2025-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_account_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales', 'Nhân viên bán hàng'), ('Product_manager', 'Nhân viên quản lý sản phẩm')], max_length=50, unique=True),
        ),
    ]
