# Generated by Django 5.1.7 on 2025-03-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_employee_is_active_alter_role_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
