# Generated by Django 5.1.7 on 2025-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_employee_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
