# Generated by Django 5.1.7 on 2025-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
