# Generated by Django 5.1.7 on 2025-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customer_customerid_alter_role_roleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roleID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
