# Generated by Django 5.1.7 on 2025-03-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_role_roleid_alter_role_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roleID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales', 'Nhân viên bán hàng'), ('Product_manager', 'Nhân viên quản lý sản phẩm')], max_length=50, unique=True),
        ),
    ]
