# Generated by Django 5.1.7 on 2025-03-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
