# Generated by Django 5.1.7 on 2025-03-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
