# Generated by Django 5.1.7 on 2025-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
