# Generated by Django 5.1.7 on 2025-03-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalogID', models.AutoField(primary_key=True, serialize=False)),
                ('catalogName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('originID', models.AutoField(primary_key=True, serialize=False)),
                ('originName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierID', models.AutoField(primary_key=True, serialize=False)),
                ('supplierName', models.CharField(max_length=255, unique=True)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitID', models.AutoField(primary_key=True, serialize=False)),
                ('unitName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineID', models.AutoField(primary_key=True, serialize=False)),
                ('medicineName', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('ingredients', models.TextField()),
                ('stockQuantity', models.PositiveIntegerField(default=0)),
                ('importPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.catalog')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.origin')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.unit')),
            ],
        ),
    ]
