# Generated by Django 5.1.7 on 2025-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicineID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='origin',
            name='originID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unitID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
