# Generated by Django 5.1.7 on 2025-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_medicineid_alter_origin_originid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='catalogID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
