# Generated by Django 5.1.7 on 2025-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_catalog_catalogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
