# Generated by Django 5.1.7 on 2025-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ingredients',
            field=models.CharField(max_length=255),
        ),
    ]
