# Generated by Django 5.1.7 on 2025-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_alter_medicine_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
