# Generated by Django 5.1.7 on 2025-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_alter_medicine_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
