# Generated by Django 5.1.7 on 2025-03-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_alter_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplierID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
